root_path : "./datasets/00.processed_csv_file_ssp/"
seq_len : 15

batchSize : 100
epoch : 30
patience : 10
validation : True
valid_portion : 0.1

model :
  name : "srgnn" # ["srgnn", "lstm", "gru"]
  srgnn :
    hiddenSize : 256
    step : 3
    lr : 0.001
    lr_dc : 0.9
    lr_dc_step : 1
    l2 : 0.999
    nonhybrid : True

  lstm :
    hidden_size : 256
    num_layers : 3
    dropout : 0.0
    lr : 0.001
    lr_dc : 0.1
    lr_dc_step : 3
    l2 : 0.0001
  
  gru :
    hidden_size : 256
    num_layers : 3
    dropout : 0.0
    lr : 0.001
    lr_dc : 0.1
    lr_dc_step : 3
    l2 : 0.0001
